apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bibeautest
  description: Sonder Helm Component.
  annotations:
    'backstage.io/kubernetes-label-selector': app.kubernetes.io/managed-by=Helm
    #github.com/project-slug: backstage/backstage
    # backstage.io/techdocs-ref: url:https://github.com/backstage/backstage
spec:
  type: service
  owner: platform@sonder.com
  lifecycle: experimental
